services:
  - type: web
    name: apex-telemetry
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///apex_telemetry.db
